name: Lint

on:
  merge_group:
  pull_request:
  push:
    branches: main

permissions:
  contents: read
  checks: write

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.
# Ensures that we don't waste CI time, and returns results quicker.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUSTFLAGS: "-Dwarnings"

jobs:
  fmt:
    name: Formatting
    runs-on: github-hosted-small
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: rustfmt
      - name: Check formatting
        uses: actions-rust-lang/rustfmt@559aa3035a47390ba96088dffa783b5d26da9326 # v1.1.1

  clippy:
    name: Clippy
    runs-on: github-hosted-small
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          components: clippy
      - name: Run clippy
        uses: auguwu/clippy-action@94a9ff2f6920180b89e5c03d121d0af04a9d3e03 # 1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # doc:
  #   name: Doc
  #   runs-on: github-hosted-small
  #   env:
  #     RUSTDOCFLAGS: -Dwarnings
  #   steps:
  #     - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
  #     - name: Setup Rust toolchain
  #       uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
  #       with:
  #         # Run docs generation on nightly rather than stable. This enables features like
  #         # https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html which allows an
  #         # API be documented as only available in some specific platforms.
  #         toolchain: nightly
  #     - name: Install cargo-docs-rs
  #       uses: dtolnay/install@cargo-docs-rs
  #     - name: Generate documentation
  #       run: cargo docs-rs